version: '2'

services:
  metrictank:
    hostname: metrictank
    image: metrictank:latest
    build: .
    ports:
     - "2003:2003"
     - "6060:6060"
    expose:
     - 6060
    volumes:
      - ./config-test/metrictank.ini:/etc/metrictank/metrictank.ini
      - ./config-test/storage-schemas.conf:/etc/metrictank/storage-schemas.conf
      - ./config-test/storage-aggregation.conf:/etc/metrictank/storage-aggregation.conf
    environment:
     WAIT_HOSTS: cassandra:9042,kafka:9092
     WAIT_TIMEOUT: 60
     MT_KAFKA_MDM_IN_GOGC_STARTUP: 40
     GOGC: 200
    links:
     - cassandra

  kafka:
    hostname: kafka
    image: raintank/kafka
    environment:
      ADVERTISED_HOST: kafka
      NUM_PARTITIONS: 8
    ports:
      - "2181:2181"
      - "9092:9092"
      - "9999:9999"
    volumes:
      - /tmp/kafka-logs

  cassandra:
    hostname: cassandra
    image: cassandra:3.11
    environment:
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 256M
    ports:
     - "9042:9042"

  graphite:
    hostname: graphite
    image: raintank/graphite-mt
    expose:
     - 80
    environment:
      GRAPHITE_CLUSTER_SERVERS: metrictank:6060
      GRAPHITE_STATSD_HOST: statsdaemon
      SINGLE_TENANT: "1"
      WSGI_PROCESSES: 4
      WSGI_THREADS: 25

  tsdb-gw:
    hostname: tsdb-gw
    image: raintank/tsdb-gw:0.9.0
    ports:
     - "9000:80"
    volumes:
      - ./config-test/storage-schemas.conf:/etc/metrictank/storage-schemas.conf
      - ./config-test/gw/auth.ini:/etc/gw/auth.ini
      - ./config-test/gw/tsdb-gw.ini:/etc/gw/tsdb-gw.ini
    environment:
     WAIT_HOSTS: kafka:9092
     WAIT_TIMEOUT: 60
    links:
     - metrictank
     - graphite
     - kafka
